#!/bin/sh

#
# Script used by hostapps updater to flash bootloader onto internal media
#

set -o errexit

# machine specific data
uboot_file="imx-boot"
block_size=1024
seek_blocks=32
device="/dev/mmcblk0boot0"

# calculate size and md5sum of the binary to update from the update bundle
update_size=$(ls -al /resin-boot/$uboot_file | awk '{print $5}')
update_md5sum=$(md5sum /resin-boot/$uboot_file | awk '{print $1'})

let skip_bytes=${block_size}*${seek_blocks}

# calculate md5sum of the data already written to $device, using $update_size bytes and skipping $skip_bytes from $device
existing_md5sum=$(dd if=$device bs=1 skip=$skip_bytes count=$update_size status=none | md5sum | awk '{print $1}')

if [ ! "$existing_md5sum" = "$update_md5sum" ]; then
	echo "Will update u-boot on /dev/mmcblk0boot0"
	echo 0 > /sys/block/mmcblk0boot0/force_ro
	dd if=/resin-boot/${uboot_file} of=${device} conv=fdatasync seek=$seek_blocks bs=$block_size
	echo 1 > /sys/block/mmcblk0boot0/force_ro
fi
