name: ESR

on:
  # Run at 00:00 on the second day every 3rd month (quarterly)
  # Run weekly too to keep the workflow enabled
  schedule:
    - cron: "0 0 2 */3 *"
    - cron: "6 0 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      esr-version:
        required: false
        type: string
        description: ESR version override, for example 2022.10. By default it uses the current year and month.
      os-version:
        required: false
        type: string
        description: OS ESR version override, for example 2.104. By default it uses the latest ESR branch.

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Exit on weekly runs
        if: github.event_name == 'schedule' && github.event.schedule != '0 0 2 */3 *'
        run: exit 1

  esr:
      name: Create ESR branch and tag
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 2 */3 *'
      uses: balena-os/github-workflows/.github/workflows/esr.yml@master
      secrets: inherit
