name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"
      - '20[0-9][0-9].[0-1]?[1470].x'

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@d87a79609d03e184f24c795a79a2e3d87427fe89
    secrets: inherit
